version: '3'
services:
  build:
    build: .
    volumes:
      - ./src:/app
    working_dir: /app
    command:  bash -c "cmake . && make" 

  run:
    build: .
    ports:
      - "80:80" 
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["sh", "-c", "./output && tail -f /dev/null"]
   
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t